project:
  type: website
  output-dir: docs

website:
  title: "Max Tu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: AboutMe.qmd
        text: About Me
      - project.qmd
        text: Project
      - freeforall.qmd
        text: Free for All
      - resume.qmd
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

