project:
  type: website
  output-dir: docs

website:
  title: "Max Tu"
  navbar:
    title: "Max Tu"
    left:
      - href: index.qmd
        text: Home
      - href: AboutMe.qmd
      - href: project.qmd
      - href: freeforall.qmd
      - href: resume.qmd
        

format:
  html:
    theme: 
      - zephyr
      - styles.scss
    mainfont: Inter
    toc: true
    page-layout: full

editor: visual

